services:
  fks_transformer:
    build:
      context: .
      dockerfile: shared/shared_docker/templates/Dockerfile.python
    working_dir: /app/src
    command: ["python", "-u", "app.py"]
    environment:
      TZ: America/Toronto
      SERVICE_PORT: 4500
      TRANSFORMER_SERVICE_PORT: 4500
      PYTHONPATH: /app/src:/app/shared
      PYTHONUNBUFFERED: 1
      FLASK_APP: app.py
      FLASK_ENV: production
    ports:
      - "4500:4500"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/app/logs
    networks: [fks_net]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4500/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  fks_net:
    external: true