[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fks_transformer"
version = "0.1.0"
description = "FKS Data Transformation Service"
requires-python = ">=3.9"
dependencies = []

[project.optional-dependencies]
dev = []
